{
 "title": "AWS ECS",
 "description": "Visualize AWS ECS metrics.",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "dimension_values($region,AWS/ECS,CPUUtilization,ClusterName)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "dimension_values($region,AWS/ECS,CPUUtilization,ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ecs_clusters{instance=\"172.31.47.160:9222\",job=\"ecs-exporter\",region=\"sa-east-1\"}"
    }
   ]
  },
  {
   "title": "Container Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ecs_container_instances{cluster=\"default\",instance=\"172.31.47.160:9222\",job=\"ecs-exporter\",region=\"sa-east-1\"}"
    }
   ]
  },
  {
   "title": "Container Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ecs_services{cluster=\"default\",instance=\"172.31.47.160:9222\",job=\"ecs-exporter\",region=\"sa-east-1\"}"
    }
   ]
  },
  {
   "title": "UP",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ecs_up{instance=\"172.31.47.160:9222\",job=\"ecs-exporter\",region=\"sa-east-1\"}"
    }
   ]
  },
  {
   "title": "CPUUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUReservation (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryReservation (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}